apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache2-deployment
  labels:
    run: apache2
spec:
  replicas: 3
  selector:
    matchLabels:
      run: apache2
  template:
    metadata:
      labels:
        run: apache2
    spec:
      containers:
      - name: apache2
        image: apache2
        ports:
        - containerPort: 80

